### ISSUE TITLE
Usage of `/bin/test/` in `regen_doc.g` is not portable?

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/recog#124]
I have Ubuntu 16.04.06 LTS and my `test` executable is in `/bin/usr`.

**Comment by fingolfin** [comment]
Quite likely. I was (deliberately) a bit lazy when writing that change, relying on people to complain if it didn't work for them. Using something like this should help make it more portable (except to system's whose `test` tool does not support `-ef`, but we should cross that bridge only if we ever get to it).
```
gap> path := DirectoriesSystemPrograms();;
gap> test := Filename( path, "test" );
"/bin/test"
```
So, patches are welcome :-)

**Comment by ssiccha** [comment]
> So, patches are welcome :-)

Done :)
