### ISSUE TITLE
FindHomMethodsPerm.VeryFewPoints: very few, or very few and small?

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/recog#141]
From the documentation for `FindHomMethodsPerm.VeryFewPoints`:
> If a permutation group acts only on a few points (the current limit is at most 10 points) then a stabiliser chain is computed by the randomized GAP library function for that purpose.

This suggests to me that it makes a stabiliser chain for `G` if `NrMovedPoints(G) <= 10`. But it's actually only making a stabiliser chain if `IsSubset([1..10], MovedPoints(G))`, i.e.:
```
if LargestMovedPoint(G) <= 10 then
  return FindHomMethodsPerm.StabChain(ri, G);
fi;
return NeverApplicable;
```
Which behaviour do we want? In either case, I think we should update the documentation here, and possibly the name of this function, to make it crystal clear what is happening.

**Comment by wilfwilson** [comment]
I'll note that `FindHomMethodsPerm.ThrowAwayFixedPoints`, which is the second most highly-ranked method in `FindHomDbPerm` (in particular, it is more highly ranked than `FindHomMethodsPerm.VeryFewPoints`) calculates `NrMovedPoints` in its first few lines. So it would be silly to argue that it is too expensive to compute `NrMovedPoints` in `FindHomMethodsPerm.VeryFewPoints`.

**Comment by ChrisJefferson** [comment]
I agree the documentation is inconsistent with the method. I don't have enough intuition to know if, given a group which acts on (say) [1,10,100,1000], we would prefer to just build a stabilizer chain directly, or first use ThrowAwayFixedPoints to map it to a group on [1,2,3,4], then find a stabilizer chain for that group.

**Comment by fingolfin** [comment]
If one wants optimal performance and fine tuning, then one probably needs to merge `VeryFewPoints` and `ThrowAwayFixedPoints` anyway. And then start benchmarking whether "10" is really the best bound. And so on. But for now, the clean design of having them separate is a win, I think. So I wouldn't worry about these fine details too much at this point. That's not to say they are irrelevant, just that we have bigger fish to fry; and whatever is "optimal" for these two methods will likely heavily depend on the other methods. So tuning them now probably will just be a waste of time.

But of course I might be wrong about this, too *shrug*

That said, adjusting the documentation to match reality of course still is desirable!

**Comment by wilfwilson** [comment]
I'll update the doc to match the current behaviour.
