### ISSUE TITLE
Documentation currently doesn't compile

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/recog#146]
This broke when #145 was merged (I didn't try compiling the documentation when I approved the PR, whoops!). I'm not very familiar with autodoc, so I'm not going to dig into it beyond yet the 10 minutes I just spent. Hopefully someone more familiar with auto doc will be able to sort it out easily.

**Comment by fingolfin** [comment]
Fixed in 7ad62c3ce7e5384267e918a7689d6fa55056e9fd, sorry about that.
