### ISSUE TITLE
Put the recognition method HowTo somewhere people can find it

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/recog#148]
We wrote this during the summer school: https://hackmd.io/UQHK8XZgSJyZrUMEzb_6eQ?both

But of course nobody will find it there. It should instead be in a Wiki, or an .md file in the repository, or part of the manual, or multiple of the above (though if we put it into multiple places, we also need a way to keep them in sync).

Of course the document also certainly could be further improved, but that's a separate concern.

**Comment by PaulaHaehndel** [comment]
Places where I would look for such a thing are:
- the Wiki on GitHub
- the documentation of the package
- (maybe) a file in the package directory (but there are already quite some files there)
- maybe the `README.md`

In some of the places (especially the `README.md`) a link would in my opinion be sufficient, which would solve the probably of keeping them in sync.

Is there a plan of integrating it in the documentation?

**Comment by fingolfin** [comment]
There is no plan, somebody needs to come up with one and do it. I was kinda hoping it wouldn't have to be me again, but I'll eventually do it, I just have many other things with higher priority on my plate.

**Comment by PaulaHaehndel** [comment]
I will have a thought about it.

**Comment by ssiccha** [comment]
I'll put it into the manual.
