### ISSUE TITLE
Wiki on GitHub is out of date resp. contains broken links

### ISSUE THREAD

**Issue by PaulaHaehndel** [gap-packages/recog#162]
Currently the [Wiki](https://github.com/gap-packages/recog/wiki) is out of date.

- There is a brocken link [https://gap-system.org/mailman/listinfo/recog](https://gap-system.org/mailman/listinfo/recog) to the information about the mailing list.

Also on [How-to-contribute](https://github.com/gap-packages/recog/wiki/How-to-contribute)
- the broken link apears in [recog mailing list](https://gap-system.org/mailman/listinfo/recog).
- We probably also don't want people to make pull requests to [recogbase](https://github.com/gap-packages/recogbase) any longer.

Is there a correct link for information about the mailling list? Is it just a temporary failure of the link?
Do we ever want to mention `recogbase` at some point?

**Comment by fingolfin** [comment]
I fixed all of these. Sorry for taking so long, but I simply didn't see this issue.

**Comment by PaulaHaehndel** [comment]
Thank you.
