### ISSUE TITLE
Implement sporadic naming as in magma

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/recog#196]
See the discussion in #195. Implementing the `RecognizeSporadic` function from magma is straight-forward. In magma it is called with the orders of at least 500 random group elements. So it might be a little bit slower then `SporadicsByOrders` which we currently use and which uses about 120 random elements. If the magma function turns out to be a lot more accurate though, we could get rid of `SporadicsByOrders`.

**Comment by fingolfin** [comment]
It would be good to find out (e.g. by asking Eamonn) what the provenance of `RecognizeSporadic` is -- is there e.g. a paper reference? And what are the assumptions this function makes exactly? From a glance at it, I'd guess that it assumes that one already ruled out (probabilistically at least) that the group is alternativ, symmetric etc.  Correct?

Also, it's not clear to me how the Magma code deals with Schur covers of the sporadic groups? It seems to me that `RecognizeSporadic` assumes there is no center? I may be misunderstanding here something, though?

**Comment by ssiccha** [comment]
I've asked Eamonn. Let's see. :)
