### ISSUE TITLE
Merge recog and recogbase?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/recog#20]
I wonder whether the seperation between recog and recogbase (still?) makes sense. The only reason I could think of _for_ it is that it marginally helps to separate the central recognition machinery from specific recognition method implementations. However, this could also be achieved by moving the code for all the recognition methods into a subdirectory, and also add clear explanantions in the README resp. manual as to which source file is responsible for what. (Indeed, we should also separate the various recognition methods better than they are right now -- and we could and should do that without moving each into a separate package ;-).

Are there any reasons for keeping the split? I'd like to hear them.

On the _downside_, the split means that a user can run into problems if they update recog but not recogbase on their system, or vice versa. It also means that refactoring efforts has to be performed on two packages simultaneously, which is errorprone.

**Comment by hulpke** [comment]
I think part of the reason was to allow for different authorship. Given the current status, I think that reason has gone. I'd be happy to move all in one.

**Comment by fingolfin** [comment]
Done via PR #25
