### ISSUE TITLE
In GH actions use docker containers with prebuilt GAP

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/recog#203]
@fingolfin  in #202:
> On the long run, we could also investigate using Docker containers with prebuilt GAP. See https://github.com/homalg-project/CatReps/blob/master/.github/workflows/Tests.yml and https://github.com/homalg-project/homalg_project/blob/master/.github/workflows/Tests.yml

**Comment by fingolfin** [comment]
If this is done, then on a global level, for everything in the gap-packages organization. No need to have a separate issue for this here
