### ISSUE TITLE
Remove use of obsolete SHALLOW_SIZE

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/recog#30]
There is one use of `SHALLOW_SIZE`. It is obsolete and should be replaced by `SIZE_OBJ`, see

https://github.com/gap-system/gap/blob/262e53d0513b507ad187278f28557245e8345cd4/lib/obsolete.gd#L595

**Comment by fingolfin** [comment]
Done in 6d8b94f585352b66b1d7d51ed8366c470568c18b
