### ISSUE TITLE
AtlasGenerators(name,integer) isn't stable

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/recog#71]
`tst/quick/ProjLowIndex2.tst` contains:

```
gap> gens := AtlasGenerators("HS",10).generators;;
gap> g := GroupWithGenerators(gens);;
gap> ri := RECOG.TestGroup(g,true,44352000);;
```

The `true` marks the group as projective, but `AtlasGenerators("HS",10)` is a permutation group (on my machine). I think these values change over time. We should switch to another means of picking out groups which is stable (if these numbers are not).

**Comment by fingolfin** [comment]
I already fixed this in 7aa9db2e5d49e0169dc90cb49ff30714da05610a Sunday night by changing it to `ag := AtlasGenerators([ "HS", [ "HSG1-f2r56B0.m1", "HSG1-f2r56B0.m2" ], 1, 2 ]);;`
