### ISSUE TITLE
Document `jellyfish` methods

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/recog#75]
Code in `gap/snksetswrsr.gi` mentions jellyfishes. Which paper is this based on?

A reference should be added to the source code.

A link to the paper could be added like in PR #73.

**Comment by fingolfin** [comment]
Maybe @DominikBernhardt or @aniemeyer can help with this?

**Comment by DominikBernhardt** [comment]
It's this paper:
A reduction algorithm for large-base primitive permutation groups by 
Maska Law, Alice C. Niemeyer, Cheryl E. Praeger and Ákos Seress

**Comment by ssiccha** [comment]
Nice. :)

The [source code] (https://github.com/gap-packages/recog/blob/623a70932889c70d90cb12ffd1817517c0f98f89/gap/snksetswrsr.gi#L32) also mentions a paper by BLS. Any idea what that could be?

**Comment by DominikBernhardt** [comment]
I think they are talking about [this paper by Babai, Luks and Serres](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.219.3040).

**Comment by fingolfin** [comment]
Awesome, thanks. Would be nice if somebody made a PR with those papers added to the bib file, and ideally also with XML Cite commands referencing them from a suitable place (e.g. the AutoDoc comment for the recog method in question).

**Comment by wilfwilson** [comment]
My PR #106 adds these two papers to the bib file, while @ssiccha is citing them in the correct place in #110.
