### ISSUE TITLE
Resolve confusing naming: "ThreeElementOrders" vs "TwoElementOrders"

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/recog#94]
I think the correct name is the one with "Three", and "Two" is just a leftover from an old version of the paper... but I might be wrong...

**Comment by fingolfin** [comment]
Actually I am not so sure anymore about my earlier remark; the code truly seems to use two element orders. Or perhaps there really are two different algorithms at play here? In any case: this needs to be resolved.

**Comment by fingolfin** [comment]
From almostsimple.gi:
> # "Large element orders and the characteristic of Lie-type simple groups."
> # by Kantor and Seress, Journal of Algebra 322 (2009) 802–832.

That should help resolving this. Also, this should be added to the bib in the manual, and be integrated into the AutoDoc comment for `FindHomMethodsProjective.ThreeLargeElOrders`

**Comment by ssiccha** [comment]
Fixed by #216.
